//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanInfo
    {
        public int ID { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string AgenterName { get; set; }
        public int Mount { get; set; }
        public bool Enable { get; set; }
        public string MarketLevel { get; set; }
        public int TypeFlag { get; set; }
        public int SortID { get; set; }
    }
}
