//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vivoEntities : DbContext
    {
        public vivoEntities()
            : base("name=vivoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AiQiYiInfo> AiQiYiInfo { get; set; }
        public virtual DbSet<LogInfo> LogInfo { get; set; }
        public virtual DbSet<PlanInfo> PlanInfo { get; set; }
        public virtual DbSet<PrizeResultInfo> PrizeResultInfo { get; set; }
        public virtual DbSet<ProfilesInfo> ProfilesInfo { get; set; }
        public virtual DbSet<RuleInfo> RuleInfo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<WechatMsgInfo> WechatMsgInfo { get; set; }
    }
}
